---
- name: Criando diretorios do App
  file: path={{item}} state=directory
  with_items:
    - /opt/giropops
    - /opt/giropops/logs
    - /opt/giropops/conf
  register: criando_diretorios

- name: Copiando o arquivo do deployment do app para o host
  template: 
    src: app-v1.yml.j2
    dest: /opt/giropops/app-v1.yml
    owner: root
    group: root
    mode: 0644
  register: copia_deployment

- name: Copiando o arquivo do services do app
  copy:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
  with_items:
    - { src: 'service-app.yml', dest: '/opt/giropops/service-app.yml'}
  register: copia_service

- name: Criando o deployment do app
  shell:
    cmd: kubectl apply -f /opt/giropops/app-v1.yml
  register: deploy_app

- name: Criando o service do app
  shell:
    cmd: kubectl apply -f /opt/giropops/service-app.yml
  register: deploy_service