---
- hosts: webserver
  become: yes
  remote_user: root
  tasks:
  - name: Instalando o Nginx
    dnf:
      name: nginx
      state: latest
      cacheonly: no
  - name: Habilitando o strat Nginx no boot
    service:
      name: nginx
      enabled: yes

  - name: Iniciando o Nginx
    service: 
      name: nginx
      state: started

  - name: Copiando HTML personalizado
    template:
      src: index.html.j2
      dest: /usr/share/nginx/html/index.html
  
  - name: Copiando Config Nginx personalizado
    copy:
      src: nginx.conf
      dest: /etc/nginx/nginx.conf
    notify: Restartando o Nginx   

  handlers:
  - name: Restartando o Nginx
    service:
      name: nginx
      state: restarted   

