- name: Instalando dependencias
  apt:
    name: 
      - python3
      - python3-pip
    state: present
    update_cache: yes
  register: instala_depencias

- name: Instalando depencencias de modulos Python
  pip:
    name: 
      - PyYAML
      - openshift
    executable: pip3
  register: pip_modules

- name: Copiando o arquivo de deployment da app v1
  template:
    src: app-v1.yml.j2
    dest: /opt/giropops/app-v1.yml
    owner: root
    group: root
    mode: 0644
  register: copy_deploy_app_v1

- name: Copiando o arquivo de deployment da app v2
  template:
    src: app-v2.yml.j2
    dest: /opt/giropops/app-v2.yml
    owner: root
    group: root
    mode: 0644
  register: copy_deploy_app_v2

- name: Deploy da app-v2
  k8s:
    state: present
    src: /opt/giropops/app-v2.yml

- name: Scale down da app-v1
  k8s:
    state: present
    src: /opt/giropops/app-v1.yml

- name: Dentro de 2 minutos o app-v1 serea removido. Pressione ctl+c para cancelar
  pause:
    minutes: 2

- name: Removendo o app-v1
  k8s:
    state: absent
    src: /opt/giropops/app-v1.yml