- hosts: all
  become: yes
  user: ubuntu
  gather_facts: no
  pre_tasks:
  - name: 'Atualizando o repo'
    raw: 'apt-get update'
  - name: 'Instalando o Python'
    raw: 'apt-get install -y python'
  roles:
  - { role: install_k8s, tags: ["install_k8s_role"] }

- hosts: k8s-master
  become: yes
  user: ubuntu
  roles:
  - { role: create_cluster, tags: ["create_cluster_role"] }

- hosts: k8s-workers
  become: yes
  user: ubuntu
  roles:
  - { role: join_workers, tags: ["join_workers_role"] }

- hosts: k8s-master
  become: yes
  user: ubuntu
  roles:
  - { role: install_helm, tags: ["install_helm_role"] }

- hosts: k8s-master
  become: yes
  user: ubuntu
  roles:
  - { role: deploy_k8s_monitor, tags: ["deploy_k8s_monitor_role"] }