- name: Criando o Sec Group
  local_action:
    module: ec2_group
    name: "{{ sec_group_name }}"
    description: sg giropops
    profile: "{{ profile }}"
    region: us-east-1
    rules:
    - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0
        rule_desc: SSH
      rules_egress:
      - proto: all
        cidr_ip: 0.0.0.0/0
    register: basic_firewall
