- name: Criando o Sec Group
  local_action:
    module: ec2_group
    name: "{{ sec_group_name }}"
    description: sg giropops
    profile: "{{ profile }}"
    region: {{ region }}
    rules:
    - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0
        rule_desc: SSH
      rules_egress:
      - proto: all
        cidr_ip: 0.0.0.0/0
    register: basic_firewall

- name: Criando a instancia EC2 
  local_action: ec2 
    group={{ sec_group_name}}
    instance_type={{ instance_type }}
    image={{ image }}
    profile={{ profile }}
    wait=true
    region={{ region }}
    keypair={{ ansible-class }}
    count={{ count }}
